### ISSUE TITLE
Create a unique ID for each vulnerability (previously GC#169)

### ISSUE THREAD

**Issue by dorindareyna** [denimgroup/threadfix#21]
Reported by brian.ma...@gmail.com, Nov 9, 2012 
Create a unique ID for each vulnerability/application

**Comment by dancornell** [comment]
We have the ability to attach a unique ID an application (and have had that since at least 2.0) This allows for integration with asset management (and other) systems. Giving specific vulnerabilities specific IDs (beyond the DB key they are assigned) doesn't really make as much sense. Closing out for now.
