### ISSUE TITLE
Nested Groups or Tagging capability

### ISSUE THREAD

**Issue by KrisCurylo** [denimgroup/threadfix#226]
I would like to request the ability to nest groups or add tags to applications. I have prod and pre-prod versions of applications as well as grouping them by business unit and potentially other tags could be added (application exposure, SOX, PCI, etc.)

**Comment by stevespringett** [comment]
What's the status of this? There's no milestone, statement of rejection, or commit tag to let us know why this is closed.

**Comment by dancornell** [comment]
Yeah sorry that is because of the way our internal JIRA integrates with GitHub. We've added application tagging to the 2.2 development cycle (you can also tag comments made to vulnerabilities. The tagging is available in recent 2.2 milestone builds, including the 2.2M6 that is online now:
http://www.denimgroup.com/blog/denim_group/2015/01/threadfix-2m6-now-available.html
